### ISSUE TITLE
Feeling Lucky

### ISSUE THREAD

**Issue by Prooofilbild** [SteamDatabase/MonsterMinigame#10]
I became no Boss Loot.

**Comment by Contex** [comment]
"Feeling Lucky" isn't related to boss loot, as per description: "Grant every alive player in your lane one random special item.<br><br>This item can only be acquired by spending badge points."

Did you mean that you used "Feeling Lucky" and didn't get any loot? Were you by any chance dead when you did that?

Do you remember if using "Feeling Lucky" while dead in the original game worked?

**Comment by Prooofilbild** [comment]
@Contex I wasn't dead. Once I used when I wasn't dead and 1 hour later another one used it and I still became no "special item".

**Comment by Contex** [comment]
This seems related to desync between the client and the server, I'll keep an eye on this for the next test, I cannot reproduce this at the moment.

**Comment by e314** [comment]
Feeling lucky while dead didn't work in the original version.

**Comment by xPaw** [comment]
I believe this is no longer an issue.
