### ISSUE TITLE
BOSS Loot

### ISSUE THREAD

**Issue by Prooofilbild** [SteamDatabase/MonsterMinigame#11]
I have 35% Chance to become a Boss item after Boss is defeated, we passed 20+ yet, no Boss Item.

**Comment by Contex** [comment]
Was this during a wormhole level skip, or just normal levels?

**Comment by Prooofilbild** [comment]
@Contex Normal Levels. Every 10th Level is a (mini?)boss. These would drop Loot sometimes(Chances) And we passed more than 15+ Bosses. With a 35% Chance to get nothing in 15 times, is really unlikely.

**Comment by Contex** [comment]
I'll check it out, doing some testing on a local copy, thanks for reporting.

**Comment by JanfoxOnSteam** [comment]
Display Base Loot in Tooltip might have something to do with the "Feeling Lucky" and no Boss Loot problem.

**Comment by Contex** [comment]
Double checked, boss loot is working as it should.

**Comment by xPaw** [comment]
Probably related to #20
