### ISSUE TITLE
Buying HP upgrades while dead revives you

### ISSUE THREAD

**Issue by Contex** [SteamDatabase/MonsterMinigame#12]
Don't revive the player if he/she purchases HP upgrades while dead.

**Comment by Autositz** [comment]
1. This will make survive in higher levels almost impossible if you can not buy HP upgrades while dead.
2. You sure nobody else revived you while you happen to click the upgrades?

**Comment by Contex** [comment]
Did the original game revive you when you bought a HP upgrade while dead? And yes, I'm sure.

**Comment by Marlamin** [comment]
@Contex I think it did actually revive you. Not sure though.

**Comment by xPaw** [comment]
@Marlamin it didn't. I remember joining high level rooms and buying hp upgrades while being dead.

**Comment by Prooofilbild** [comment]
@Marlamin I could remember that I bought some HP Upgrades when I was dead. Wasn't revived. [Official]

**Comment by Marlamin** [comment]
Okay I suck

**Comment by Autositz** [comment]
@Marlamin Don't let Timmy know!

**Comment by Contex** [comment]
Fixed in 0.9.8
