### ISSUE TITLE
Cripple Monster Ability Doesn't Activate

### ISSUE THREAD

**Issue by Rorroh** [SteamDatabase/MonsterMinigame#16]
The ability "Cripple Monster" doesn't activate when it is clicked on.  It just stays in inventory.

Player Yuri confirms this, and adds that it seems to only work for minions.

**Comment by Contex** [comment]
The ability currently only activates when the current target is a "mob" or a "miniboss". As per description: "Reduces player's current target to 1 HP for normal monsters or up to 5% max health for a boss monster."

Did this ability work on all monsters in the original game, even bosses, spawners?

**Comment by e314** [comment]
It removed 5% max HP for a boss, and worked on creepers as it did on minions.

**Comment by Contex** [comment]
@e314 alright, so up to 5% for bosses, and 1 HP for everything else (even spawners/towers?)

**Comment by e314** [comment]
No idea what you call "tower". If it's the side-kicks of bosses, I don't know.
It worked on spawners (I might have played too much minecraft and typed creepers instead..)

**Comment by Contex** [comment]
Fixed in 0.9.8. The ability will do up to 5% max HP damage for the boss, and set every other monster down to 1 HP.

Thanks @e314!
