### ISSUE TITLE
Stats aren't counted correctly

### ISSUE THREAD

**Issue by Contex** [SteamDatabase/MonsterMinigame#20]
I'm positive we killed more than 1 boss.

num_players 720
num_mobs_killed 1370
num_towers_killed 430
num_minibosses_killed 130
num_bosses_killed 1
num_treasures_killed 0
num_clicks 954354
num_abilities_activated 3459
num_players_reaching_milestone_level 0
num_ability_items_activated 2334
num_active_players 15
time_total_ticks 445.1474364
time_slowest_tick 0.0640011

**Comment by Contex** [comment]
Double check the the percentage chance for spawning treasure mobs is correct

**Comment by xPaw** [comment]
I've fixed treasure mob spawning.

**Comment by Contex** [comment]
I can't reproduce this, will have to check num_bosses_killed the next couple of testing rounds we do.

**Comment by xPaw** [comment]
Boss killing isn't counted when the boss is killed using a nuke.

**Comment by Contex** [comment]
Fixed in 0.9.8.
Also fixed that if a boss gets killed by a nuke, there will also be a chance to drop loot, this wasn't working before.
