### ISSUE TITLE
Should we still count Ressurection as used if no players were revided?

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/MonsterMinigame#35]

**Comment by e314** [comment]
Same as "should we count a nuke used if there was no creep on the lane?".
Or : should we count "like new" used if everyone had all their cooldowns ready?
For me, the answer is "obviously yes", but I'm always open to arguments.

**Comment by Contex** [comment]
Nuke wasn't used when there was no monsters in the lane or the current target was dead. Which is why this is up for discussion, if I recall correctly "Like New" was used no matter if people had their cooldowns wiped or not.

**Comment by e314** [comment]
Nuke was unused (I think, never checked but I remember seeing this written somewhere), but "damage the spawner" and "damage the monsters" were.
(And I don't even know why it was unused. I'd say that if there are no monsters to target, the nuke should fall on the player instead.)

**Comment by Contex** [comment]
That is a funny idea, it could be an issue if there's a desync between the player and the server though.

**Comment by xPaw** [comment]
I've implemented this, since other abilities don't get used up if they don't do anything (no target, etc).
