### ISSUE TITLE
Missing morale booster

### ISSUE THREAD

**Issue by e314** [SteamDatabase/MonsterMinigame#53]
I don't remember what it did. Probably quite useless. But when we reached lv 30 in armor piercing rounds, it unlocked the "morale booster" (with the blue head icon looking like a ghost from pacman) for 10M.
I think it had 30 min cooldown.

**Comment by Contex** [comment]
I saw someone use during the test today, will test and debug it after the test today.

**Comment by e314** [comment]
It's linked with auto-fire. I might remember this badly.

**Comment by Contex** [comment]
It's linked to auto-fire, and the required level is 20, I just tested it and it worked just fine?
