### ISSUE TITLE
[SELFFIXED]Cripple Monster

### ISSUE THREAD

**Issue by Prooofilbild** [SteamDatabase/MonsterMinigame#6]
Can't use it. Already reloaded the Page(f5). Is the Info not updated?

**Comment by Contex** [comment]
Is it showing up in your abilities bar?
Any errors in javascript console?

**Comment by Prooofilbild** [comment]
@Contex it removed itself now, after I pressed f12 in Chrome for Console. Wierd. (No Errors)
