### ISSUE TITLE
No mobs seem to spawn

### ISSUE THREAD

**Issue by CosmicHikari** [SteamDatabase/MonsterMinigame#68]
So I installed this on my own web server just to mess around. I set the APIKey properly in config.json but no mobs spawn after logging in. Anyone got any ideas? 

![image](https://cloud.githubusercontent.com/assets/16886014/17270051/155e6e22-5627-11e6-93d0-63e6a92f8584.png)

When looking into console it looks as if it needs a backend server but can not be reached. Anyone have any ideas on it?

**Comment by CosmicHikari** [comment]
It is as if the initializer can not reach :5337 and just times out or gives error 500

**Comment by Luukuton** [comment]
Yup, same problem on Debian 8 with NGINX 1.11.3.

Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://my.domain.com/api/ITowerAttackMiniGameService/GetPlayerData/v0001/?gameid=1&steamid=76561198264631733&include_tech_tree=1&include_stats=1

**Comment by xPaw** [comment]
Did you start the backend server and is it not firewalled?

**Comment by CosmicHikari** [comment]
How do I do that?

**Comment by xPaw** [comment]
It's in php/ folder.

**Comment by CosmicHikari** [comment]
Do I just open server.php via my browser or something?

**Comment by xPaw** [comment]
You need a proper server to run it as a background process.

**Comment by CosmicHikari** [comment]
I have Nginx so I just need to figure a way to run it as a server now. Thanks for the input!

**Comment by AliceTS1337** [comment]
I'm having the exact same problem. I'm using XAMPP and I'm not sure how I'd launch the backend server.
