### ISSUE TITLE
Raining Gold

### ISSUE THREAD

**Issue by Prooofilbild** [SteamDatabase/MonsterMinigame#7]
Happened like this: Someone used 1x Raining Gold: 641k per click. 2x Raining Gold active: 671k. It doesn't multiplicated.

**Comment by Contex** [comment]
Did Raining Gold multiply in the original version? I know they stacked, but I don't think the percentage ever went above 200%, thus increasing by 1% percent per raining gold instead. Could anyone confirm?

**Comment by ghost** [comment]
@Contex 

They actually multiplied up to 200% and then I'm pretty sure it was additional 25% afterwards per stack.

**Comment by Contex** [comment]
Fixed in 0.9.8
